perf: optimize pfd and simconnect requests
flybywiresim/aircraft pull request #7835
Opened 2023-02-28 10:50 UTC by Saschl

Fixes #[issue_no]

## Summary of Changes

 - Removes usages of SIMCONNECT_PERIOD_ONCE as it's not recommended for regularly requesting data (https://docs.flightsimulator.com/html/Programming_Tools/SimConnect/API_Reference/Structures_And_Enumerations/SIMCONNECT_PERIOD.htm?rhhlterm=SIMCONNECT_PERIOD_ONCE&rhsearch=SIMCONNECT_PERIOD_ONCE)
 - PFD drawing optimizations
   - Reduce amount of unnecessary draws
   - Use translate3d for translation to make use of GPU acceleration

## Screenshots (if necessary)

## References

## Additional context

Discord username (if different from GitHub):

## Testing instructions

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2023-05-08 10:05 UTC, tracernz commented on fbw-a32nx/src/systems/instruments/src/PFD/SpeedIndicator.tsx
> +                    id="UpperSpeedMargin"
```suggestion
                    id="LowerSpeedMargin"
```

2023-05-08 10:05 UTC, tracernz commented on fbw-a32nx/src/systems/instruments/src/PFD/AttitudeIndicatorHorizon.tsx
> +            this.heading = h.value;
Seems a backwards step to discard the SSM, and in this case it should check the SSM.

2023-06-11 16:18 UTC, Saschl commented
I see there's a lot more to optimize/cleanup, however that would be suitable for another PR. Main goal here was to fix the FMA borders being constantly changed and to get rid of SIMCONNECT_PERIOD_ONCE

2023-07-21 13:56 UTC, BlueberryKing requested changes

2023-07-21 13:56 UTC, BlueberryKing commented on fbw-a32nx/src/systems/instruments/src/PFD/AttitudeIndicatorHorizon.tsx
> +        return false;
```suggestion
        return !fdActive && attitude.isNormalOperation() && heading.isNormalOperation() && inRange
```

2023-07-23 11:18 UTC, BlueberryKing approved these changes
Nice work!

2023-07-23 13:19 UTC, auroraisluna commented
QA Report

Discord: alepouna
Object of testing: #7835 
Tier of Testing : 1
Date : 23/7/2023

Testing Process:
- Spawn in airport
- Observe PFD operational 
- Observe aircraft performance

Testing Results:
Passed

Notes: 
My CPU loves you Saschl. 

**FPS comparison**
Latest dev branch (at the time of writting) 
![image](https://github.com/flybywiresim/aircraft/assets/98479040/0426154e-aa9e-49fd-adb3-56bf31123244)

PR
![image](https://github.com/flybywiresim/aircraft/assets/98479040/e22fd9f3-3b9a-4e2a-8ec8-83a408d318fd)

:stonks:

2023-07-23 13:42 UTC, merged