fix(mcdu): no v-speeds without fob
flybywiresim/aircraft pull request #8165
Opened 2023-08-12 15:37 UTC by tracernz

Fixes #[issue_no]

## Summary of Changes

## Screenshots (if necessary)

## References

## Additional context

Discord username (if different from GitHub):

## Testing instructions

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2023-08-14 02:01 UTC, 2hwk requested changes

2023-08-14 02:01 UTC, 2hwk commented on fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_InitPage.js
> +                if (!!SimVar.GetSimVarValue("L:A32NX_BOARDING_STARTED_BY_USR", "bool")) {
```suggestion
                if (!!SimVar.GetSimVarValue("L:A32NX_BOARDING_STARTED_BY_USR", "bool")) {
```

For QA: Add testing instruction to testers that the auto-populate will only grab the EFB's target ZFW values if boarding is in progress

2023-08-14 08:50 UTC, tracernz commented on fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_InitPage.js
> +                    zfwCg = SimVar.GetSimVarValue("L:A32NX_BOARDING_ZFWCG_DESIRED", "number");
We only ever deal with CG in %MAC in the FMS.

2023-08-15 11:15 UTC, 2hwk approved these changes

2023-08-19 06:03 UTC, auroraisluna commented
QA Report

Discord: alepouna
Object of testing: #8165
Tier of Testing : 1
Date : 19/08/2023

Testing Process:
- [PASS] Make sure the V-speed calculation on PERF TO doesn't work until ZFW and FoB are entered on INIT B
- [PASS] Make sure the ZFW/ZFWCG auto-fill/helper uses the live weight when not boarding, and the target weights when boarding is active.

Testing Results:
Passed

Note: 
Noice.

2023-08-19 15:17 UTC, merged