feat(payload): Multiple gate boarding when multiple boarding points are opened
flybywiresim/aircraft pull request #8206
Opened 2023-09-10 03:21 UTC by 2hwk

Fixes #[issue_no]

## Summary of Changes

* Adds multiple gate boarding support
* TODO: GSX Support

## Screenshots (if necessary)

## References

## Additional context

Discord username (if different from GitHub):

## Testing instructions

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2023-09-13 05:49 UTC, tracernz approved these changes
JS side looks fine. Didn't review rust. I think we have about 4 different PRs or branches with different A380 package manifests and build scripts now so we might want to just standardise on the comprehensive work @Benjozork and @flogross89 are doing.

2023-09-14 21:15 UTC, Gurgel100 requested changes
My review from the Rust part.

2023-09-14 21:15 UTC, Gurgel100 commented on fbw-a32nx/src/wasm/systems/a320_systems_wasm/src/payload.rs
> +    );
You actually don't need this. You can add calls to `provides_aircraft_variable` (see lib.rs:290)

2023-09-14 21:15 UTC, Gurgel100 commented on fbw-a380x/src/wasm/systems/a380_systems_wasm/src/payload.rs
> +    );
You actually don't need this. You can add calls to `provides_aircraft_variable` (see lib.rs:290).

2023-09-15 18:40 UTC, Gurgel100 commented on fbw-a380x/src/wasm/systems/a380_systems_wasm/src/lib.rs
> +    .provides_aircraft_variable("INTERACTIVE POINT OPEN", "percent", 10)?
Please capitalize the unit to be consistent.

2023-09-16 12:38 UTC, Gurgel100 approved these changes

2023-09-17 13:09 UTC, auroraisluna commented
QA Report - **A32NX**

Discord: alepouna
Object of testing:  #8206
Tier of Testing : 1
Date : 17/09/2023

Testing Process:
- [PASS] Complete Boarding without any doors/jetway attached, this should work as per the usual boarding process before, then deboard the plane entirely and wait for all sounds to clear (boarding etc.)
- Go to the services page and open 2 doors (Fwd Left and Aft Left) to enable dual-gate boarding.
- Go back to the payload page and load passengers (with simbrief or manual entry)
- [PASS] The estimated boarding time displayed should be half the duration as previously (less than 10 min)
- [PASS] Start a real or fast time boarding and observe that the estimated duration is accurate, and that the passengers are shown as being filled from both the front and back of the aircraft.
- [PASS] Check that deboarding also works in exactly the same way but with the passengers being deboarded from both the front and back of the aircraft.

Testing Results:
Passed

2023-09-17 15:36 UTC, merged