fix(efb): amend dashboard weather widget to better reflect APPR phase weather input order
flybywiresim/aircraft pull request #8208
Opened 2023-09-12 13:09 UTC by oim1

## Summary of Changes
This PR changes the order weather is displayed on the flyPad's weather widget. This reordering makes it easier to read and input weather into the MCDU for the approach perf page. 

## Screenshots (if necessary)

Before:
![image](https://github.com/flybywiresim/aircraft/assets/81839029/90affa51-4f88-4a9c-bc03-05a4f1e263a7)

After:
![image](https://github.com/flybywiresim/aircraft/assets/81839029/08be6bff-aefb-4c23-8e57-4d551f90d28e)

MCDU APPR PERF page:
![image](https://github.com/flybywiresim/aircraft/assets/81839029/6701ff78-388a-412a-8ee7-9e1c5d12396b)

## References
N/A

## Additional context

Open to further discussion if this change is not necessary. 

Discord username (if different from GitHub): oim#0

## Testing instructions
1. Once loaded into aircraft, turn on flyPad. 
2. Import weather from Simbrief and check that temperature is to the left of wind speed/direction. 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2023-09-12 13:30 UTC, FoxtrotSierra6829 commented
In my opinion, where both temperature and dew point are given, they should strictly be next to each other.
In general, I‘d rather be in favor of the order being derived from standard weather reporting formats used in aviation, such as the METAR and the weather information in the ATIS rather than to adapt it to the FMS of a specific aircraft. When listening to the ATIS in real life, the correct order ensures that all relevant information is being copied and is easily identifiable.
The order matching these formats would then be wind, temperature, dew point, QNH

2023-09-12 18:36 UTC, oim1 commented
> In my opinion, where both temperature and dew point are given, they should strictly be next to each other.
> 
> In general, I‘d rather be in favor of the order being derived from standard weather reporting formats used in aviation, such as the METAR and the weather information in the ATIS rather than to adapt it to the FMS of a specific aircraft. When listening to the ATIS in real life, the correct order ensures that all relevant information is being copied and is easily identifiable.
> 
> The order matching these formats would then be wind, temperature, dew point, QNH

This is a fair point. I did not realise there was a standard format. 

I could change it to match that format if that is preferred.

2023-09-13 04:07 UTC, 2hwk commented on .github/CHANGELOG.md
> +42. [EFB] Change the order of the weather dashboard elements to reflect the order of the MCDU APPR PERF phase - @oim (oim1)
fix diff

2023-09-16 12:39 UTC, tracernz commented
The only concern I have (which is already valid, but further reinforced now) is that people will enter the true wind direction from this METAR into the PERF APPR page rather than the magnetic wind from an ATIS.

2023-09-16 21:31 UTC, FoxtrotSierra6829 commented
> The only concern I have (which is already valid, but further reinforced now) is that people will enter the true wind direction from this METAR into the PERF APPR page rather than the magnetic wind from an ATIS.

Maybe we can write the wind in the dashboard as e.g. `320°(T)/03kt` ?

2023-09-17 01:32 UTC, tracernz commented
I think we should do that. The other idea I had is to allow toggling between true and magnetic if we have the airport lat/lon available (so we can get the mag var).

2023-10-19 08:31 UTC, Lauvaan commented
This is probably a bit out of scope of this pr, but a possibility to rearrange the order the weather is displayed. If it would be possible, maybe just dragging them to different positions could be a nice idea. This feature could also be used to rearrange the other widgets(like rearranging the whole widgets) on the main screen. 

But as I said, may be a bit out of scope for this pr, for now I'd say best to either use what we have now, or probably better use the same order they're in metars/atis's.

2023-10-24 08:06 UTC, tracernz requested changes

2023-10-24 08:06 UTC, tracernz commented on .github/CHANGELOG.md
> +42. [EFB] Change the order of the weather dashboard elements to reflect the order of the MCDU APPR PERF phase - @oim (oim1)
Please keep all these 1.... markdown handles the numbering automatically. Also, move your own one to v0.12.0 (after a rebase/merge of master).

2023-12-16 01:04 UTC, Benjozork commented
@oim1 Is this still being worked on?

2025-02-02 03:25 UTC, Benjozork commented
Closing due to inactivity.

2025-02-02 03:25 UTC, closed without merging