Surprise Livery
flybywiresim/aircraft pull request #8340
Opened 2023-12-24 14:33 UTC by markszutor

Fixes #[issue_no]

## Summary of Changes

- Created a Christmas / Holidays themed livery for the Festive Season

## Screenshots (if necessary)

![image (2)](https://github.com/flybywiresim/aircraft/assets/112664262/fb47f6f8-fe8e-4ac8-936d-fd7ed7026145)
![image](https://github.com/flybywiresim/aircraft/assets/112664262/fd517ff5-9485-4a78-abc9-e098889ec7e0)

## References

## Additional context

- All credit goes to the Hues by Horizon Simulations Team and especially the original creator of the livery: SilkySmooth

Discord username (if different from GitHub):
- szutormark
- SilkySmooth
- 

## Testing instructions

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2023-12-24 18:18 UTC, FoxtrotSierra6829 requested changes

2023-12-24 18:18 UTC, FoxtrotSierra6829 commented on fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/_FlyByWire_A320_NEO-CHRISTMAS/MODEL/model.cfg
parent folder should probably be MODEL.FBW according to aircraft.cfg

2023-12-24 18:50 UTC, markszutor reviewed
Folder reference updated as requested.

2023-12-25 00:19 UTC, FoxtrotSierra6829 requested changes
Engine textures are requested to be reverted to those of the original livery

2023-12-25 02:20 UTC, FoxtrotSierra6829 commented
Testing is completed.

Can be merged if `_FlyByWire_A320_NEO-CHRISTMAS/TEXTURE.FBW/A320NEO_AIRFRAME_ENGINES_ALBD.PNG.DDS` is replaced with the file found at
`_FlyByWire_A320_NEO-LIVERY/TEXTURE.FBW/A320NEO_AIRFRAME_ENGINES_ALBD.PNG.DDS`

2023-12-25 08:02 UTC, FoxtrotSierra6829 approved these changes

2023-12-25 08:41 UTC, merged

2023-12-25 09:13 UTC, auroraisluna commented
(late) QA Report 

Discord: alepouna
Object of testing:  #8340
Tier of Testing : 1
Date : 25/12/2023

Testing Process:
Used my eyes

Testing Results:
Passed

Note: 
Very lovely! Really like the snowflake details (took me a minute to realize what they are lol) - Happy Holidays!