eat(EFB/SimBrief): Automatically import SimBrief Fuel & Payload (2nd Attempt)
flybywiresim/aircraft pull request #8470
Opened 2024-02-06 22:43 UTC by Fragtality

Fixes #7772
(Together with PR #8407)

## Summary of Changes

New in this Variant:
- Don't call fetchData when simbriefDataPending or both navigraphUsername & overrideSimBriefUserID are empty (although autoSimbriefImport is ENABLED)
- history.push Calls consolidated into one .then Block (and not called when Exception was raised)
- Toast only really displayed when both fuelImported and payloadImported are true

Old Summary:
- When SimBrief Data was imported (either manual or automatic), the Fuel & Payload Pages automatically import their Data too. Approach:
  - The Fuel and Payload Page have an useEffect to import the Data when visited (only when SimBrief Data is loaded)
  - The Import Function navigates through the Pages (Dashboard->Fuel->Payload->Dashboard)
  - Two additional Flags in the SimBrief Store prevent that Payload or Fuel are imported every time the respective Page is revisited
- Auto-Import of SimBrief Data moved from EFB.tsx to FlightWidget.tsx (to not maintain two Copies of the same Code)
- Added Setting to enable/disable that Behavior

## Screenshots (if necessary)

![flightwidget-toast](https://github.com/flybywiresim/aircraft/assets/78614902/1ff0c9fe-92f0-422f-924c-558cfdf1a537)

## References

## Additional context

Although the originating Issue is in the GSX Context, this Feature improves Comfort for everyone (using SimBrief). Only one Click needed - if at all - to get all relevant Data imported 😃 

Discord username (if different from GitHub): Fragtality

## Testing instructions

PREPARATION before installing this Build/Artifact:
1. Load into the Airplane with the current/official Dev Version
2. Unlink Navigraph (Settings > 3rd Party Options)
3. Remove SimBrief ID (Settings > 3rd Party Options)
4. Keep the automatic SimBrief Data Import enabled! (Settings > ATSU/AOC)

Test 1

1. Load into the Airplane
2. Power up the EFB => Result: No Error or Success Toasts/Messages
3. Hit "Import SimBrief Data" => Result: Only "Error: Unknown UserID" should show up
4. Preparation for next Test: set SimBrief ID (Settings > 3rd Party Options) and exit to Main Menu

Test 2

1. Prepare a Flightplan on SimBrief for the FBW
2. Load into the Airplane
3. Power up the EFB => Result: A Notification should appear (like shown in the Screenshots)
4. Navigate to the Fuel & Payload Page => Result: Each Page should display the planned Fuel / Payload from your SimBrief OFP
5. Navigate back to Dashboard => Result: No Notifications shown
6. Edit the SimBrief OFP with a different ZFW & Block-Fuel
7. Click the SimBrief Import Button on the Dashboard => Result: The Notification should appear again
8. Navigate to the Fuel & Payload Page => Result: Each Page should display the new planned Fuel / Payload
9. Preparation for next Test: disable the automatic SimBrief Data Import (Settings > ATSU/AOC) and exit to Main Menu

Test 3

1. Load into the Airplane
2. Power up the EFB => Result: No Error or Success Toasts/Messages and no Import happening
3. Hit "Import SimBrief Data" => Result: OFP imported but no Notification for Fuel & Payload is shown
4. Navigate to the Fuel & Payload Page => Result: Each Page still shows the default Values (Fuel & Payload *not* imported)

For additional Verification you can monitor the L-Vars `A32NX_FUEL_DESIRED` and `A32NX_AIRFRAME_ZFW_DESIRED` => these should immediately Change when the SimBrief Data was imported (without leaving the Dashboard).
(If you have a Tool at Hand to monitor L-Vars quick & easy)

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2024-02-15 15:32 UTC, Fragtality commented
This PR would be ready to Review / ready for Feedback. It's just in Draft in Case of a Review / Feedback would require bigger Changes / Refactoring

2024-02-24 04:01 UTC, 2hwk commented
``fbw-a32nx`` -> ``fbw-common`` as of #8473 being merged

2024-02-24 13:27 UTC, Fragtality commented
. . .

2024-02-28 02:12 UTC, 2hwk requested changes

2024-02-28 02:12 UTC, 2hwk commented on fbw-common/src/systems/instruments/src/EFB/Ground/Pages/Payload/A320_251N/A320Payload.tsx
> +    const generalBoardingInProgress = () => (gsxPayloadSyncEnabled ? gsxInProgress() : boardingStarted); // TODO this should be a Lvar and written in rust
Remove the TODO or reexamine this general boarding var.

On review now that I've had a better look I really don't like this, the rust backend has been made with the concept that GSX has its own seperate hook via the payload layer to the MSFS payload values, we don't manage this at all.

The addition of the GSX vars here was always a temporary solution, meant to be replaced by a dedicated GSX frontend. (See https://github.com/flybywiresim/aircraft/pull/8225)

2024-02-28 03:46 UTC, 2hwk approved these changes

2024-02-28 10:31 UTC, Maximilian-Reuter commented
I still need to update the Test descriptions so I would refrain from testing until I have done that

2024-03-02 14:30 UTC, alepouna commented
QA Report

Discord: alepouna
Object of testing:  #8470
Tier of Testing : 1
Date : 2/3/2024

Testing Process:
As described
- [PASS] TEST 1 
- [PASS] TEST 2
- [PASS] TEST 3
- [PASS] TEST 4
- [PASS] TEST 5

-- GSX TESTS --

- [PASS] TEST 6
- [PASS] TEST 7

Testing Results:
Passed

Note: 
GSX was installed.

2024-03-03 03:25 UTC, alepouna commented
QA Report

Discord: alepouna
Object of testing:  #8470
Tier of Testing : 2
Date: 3/3/2024

Testing Process:
As described, performed full flight. 
- [PASS] TEST 1 
- [PASS] TEST 2
- [PASS] TEST 3
- [PASS] TEST 4
- [PASS] TEST 5

Testing Results:
Passed

Note: 
GSX was NOT installed.

2024-03-03 14:28 UTC, merged