fix(fuel): Lowered C/D spawn fuel, fixed center tank refueling
flybywiresim/aircraft pull request #8502
Opened 2024-02-17 12:03 UTC by Maximilian-Reuter

Fixes #8092

## Summary of Changes

This PR aims to lower the fuel amount on C/D spawns to 2 tons. This way it reflects reality a bit better and almost always requires to refuel before flight.

Additionally I also changed the logic behind loading the saved fuel from last shutdown. Previously it would always be loaded no matter where one spawns. To me that didn't make sense as If someone wants to spawn on the runway or in the air, they are obviously forgoing refueling and therefore need a reasonable amount of fuel in the tanks. Currently that is 50% of the fuel load. 

This can be changed by adding tank levels to the FLT files if desired.

Finally fixed the longstanding issue where our plane would only fuel the center tanks after the wing tanks had been filled. In reality both center and wing tanks get filled at the same time.

## Screenshots (if necessary)

## References

## Additional context

Discord username (if different from GitHub):\_chaoz_

## Testing instructions

First make sure you are using the default FBW livery and that the A32NX.ini file in the location described here is deleted:
https://docs.flybywiresim.com/fbw-a32nx/feature-guides/loading-fuel-weight/?h=aircraftstate#fuel-persistence

1. Spawn C/D
2. Check fuel amount, should be 2 tons in only the inner tanks
3. Fill up fuel tanks completely and observe center tanks getting filled while wing tanks are filling
4. Detank fuel and observe the same in reverse
5. Spawn on runway
6. Check fuel amount to be 50% 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2024-02-23 10:58 UTC, 2hwk approved these changes

2024-02-23 10:58 UTC, 2hwk commented
Approved but we probably need to test this a bit to see what the impacts/implications will be

2024-02-24 01:53 UTC, Popespice commented
Quality Assurance Report

Discord          : Popespice
Object of testing:#8502
Tier of Testing  : 2
Date             : 23022024

Testing Process: 
1. Go into work folder and delete saved aircraft state
2. Load into game and spawn in at any airport
3. Power on plane as usual
4. Check flypad, observe plane has 2.5 tons (kilograms) of fuel onboard
5. Fill tanks to max
6. Observe wing and center tanks fuel concurrently
7. Drain tanks back to 2.5 tons
8. Observe tanks defuel concurrently
9. Spawn back in direct to runway
10. Observe fuel on flypad is at 50% marker by default

Negatives:       
N/A

Testing Results: 
Passed

Conclusions: 
Working as intended

Media:       
N/A

2024-02-24 15:45 UTC, Maximilian-Reuter commented
Waiting for @2hwk to give okay

2024-02-29 07:11 UTC, 2hwk requested changes

2024-02-29 07:11 UTC, 2hwk commented on .github/CHANGELOG.md
> +1. [Fuel] Lowered starting fuel on C/D spawn, will only load last saved fuel on C/D spawn, center tank refuel now happens simultaneous with wing refuel - @Maximilian-Reuter (\_Chaoz_)
```suggestion
1. [FUEL] Lowered starting fuel on C/D spawn, will only load last saved fuel on C/D spawn, center tank refuel now happens simultaneous with wing refuel - @Maximilian-Reuter (\_Chaoz_)
```
Fuel in caps please to match the format (I could commit this myself if needed)

2024-02-29 08:09 UTC, 2hwk commented
QA Report

- [x] Spawn C/D
- [x] Check fuel amount, should be 2.5 tons in only the inner tanks
- [x] Fill up fuel tanks completely and observe center tanks getting filled while wing tanks are filling
- [x] Detank fuel and observe the same in reverse
- [x] Spawn on runway
- [x] Check fuel amount to be 50% 

My own checks: 

- [ ] Check for slider init value matching the initial spawn fuel value - Failed

![image](https://github.com/flybywiresim/aircraft/assets/15316958/b845e4f3-b161-43d9-9f3b-dba8a7e63823)

Should be:

![image](https://github.com/flybywiresim/aircraft/assets/15316958/96f14022-6da2-4da3-a47a-d5f1a1f58ab7)

Just to confirm that it's what I suspect is going on:

![image](https://github.com/flybywiresim/aircraft/assets/15316958/ae3fb69e-3375-4ce9-9d4d-1ddc1d723ecf)

![image](https://github.com/flybywiresim/aircraft/assets/15316958/70547f2d-2bfe-43a3-aef3-75a03ee31c4d)


Looks like the line of JS that initialises the desired fuel level that controls the slider (After READY TO FLY screen) is loaded BEFORE the FADEC WASM code sets the fuel, which means the wrong fuel amount is initialised on C&D spawn.

The slider should reflect the starting spawn amount of fuel when you first load in (Yes I know this UX is not perfect or 100% intuitive, but it is what it is) 

Result:
 - QA Not Passed

2024-02-29 10:34 UTC, merged