docs(github templates): Update PR template wording for A380
flybywiresim/aircraft pull request #8538
Opened 2024-03-01 09:45 UTC by alepouna

## Summary of Changes

Quick edit of the GitHub PR template to include the A380 name and also the two new zip files accessible.

## Additional context

Discord username (if different from GitHub): alepouna

## Testing instructions

NQAN

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2024-03-01 09:46 UTC, 2hwk approved these changes

2024-03-02 16:56 UTC, Benjozork requested changes

2024-03-02 16:56 UTC, Benjozork commented on .github/PULL_REQUEST_TEMPLATE.md
> +Every new commit to this PR will cause a new A32NX & A380X artifact to be created, built, and uploaded.
Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

2024-03-02 16:57 UTC, Benjozork submitted a review, later dismissed

2024-03-02 16:57 UTC, Benjozork commented on .github/PULL_REQUEST_TEMPLATE.md
> +Every new commit to this PR will cause a new A32NX & A380X artifact to be created, built, and uploaded.
```suggestion
Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.
```

2024-03-07 10:28 UTC, tracernz approved these changes

2024-03-10 06:56 UTC, merged