refactor: Fadec rewrite using Cpp framework
flybywiresim/aircraft pull request #8547
Opened 2024-03-02 20:37 UTC by frankkopp

## Summary of Changes
Rewrite of the current fadec code to better support multi-aircraft and provide better modularity and maintainability. 

Discord username (if different from GitHub): cdr_maverick

## Testing instructions
TBD

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2024-03-27 15:40 UTC, 2hwk requested changes

2024-03-27 15:40 UTC, 2hwk commented on fbw-common/src/systems/instruments/src/EFB/Ground/Pages/Fuel/A380_842/A380Fuel.tsx
Should this diff be in this PR? This seems like a EFB related change not a CPP framework related. Unless this is intended as part of this PR?

2024-03-27 15:40 UTC, 2hwk commented on fbw-a380x/src/wasm/fadec_a380x/src/Fadec/Polynomials_A380X.hpp
> +    // Coefficients for the polynomial used to calculate the N2 percentage.
```suggestion
    // Coefficients for the polynomial used to calculate the N3 percentage.
```

2024-03-27 15:40 UTC, 2hwk commented on fbw-a380x/src/wasm/fadec_a380x/src/Fadec/Polynomials_A380X.hpp
> +   * @param currentSimN3 The current N3 value in percent (taken from the sim's N2 value).
```suggestion
   * @param currentSimN3 The current N3 value in percent (taken from the sim's N3 value).
```

2024-03-27 15:40 UTC, 2hwk commented on fbw-a380x/src/wasm/fadec_a380x/src/Fadec/Polynomials_A380X.hpp
> +    // Normalize the current N3 percentage by scaling it with the idle N2
```suggestion
    // Normalize the current N3 percentage by scaling it with the idle N3
```

2024-03-27 15:40 UTC, 2hwk commented on fbw-a380x/src/wasm/fadec_a380x/src/Fadec/Polynomials_A380X.hpp
> +   * @brief Calculates the Oil Pressure (PSI) based on simulated N2 value.
```suggestion
   * @brief Calculates the Oil Pressure (PSI) based on simulated N3 value.
```

2024-03-27 15:40 UTC, 2hwk commented on fbw-a380x/src/wasm/fadec_a380x/src/Fadec/FadecSimData_A380X.hpp
> +    engineCorrectedN3DataPtr[E4] = dm->make_datadefinition_var<CorrectedN3Data>("TURB ENG CN2 4", engine4CN3DataDef, NO_AUTO_UPDATE);
Even though this is already covered by a comment to the struct above

 > Note: the sim does not have a direct N3 value, so we use N2 as a proxy

I still think there should be a comment/note above here which again notes and refers to this, as it is important.

2024-03-27 16:04 UTC, 2hwk requested changes

2024-03-27 16:04 UTC, 2hwk commented on fbw-common/src/systems/instruments/src/EFB/Ground/Pages/Fuel/A380_842/A380Fuel.tsx
As this is intentional, please remember to add a basic testing instruction to check this page's functionality

2024-03-27 17:31 UTC, frankkopp commented on fbw-common/src/systems/instruments/src/EFB/Ground/Pages/Fuel/A380_842/A380Fuel.tsx
will do

2024-04-01 11:57 UTC, Maximilian-Reuter approved these changes

2024-04-02 13:20 UTC, 2hwk approved these changes

2024-04-08 00:37 UTC, 2hwk commented
Fix merge conflicts, then reset Ready to Test tag

2024-04-10 14:06 UTC, noonebling commented
Quality Assurance Trainee Report

Discord          : noonebling
Object of testing: 8547
Tier of Testing  : 2
Date             : 10/04/2024

Testing Process: 
Full regression tests on the A32NX with full flights from c&d, runway and the air.
Fuel handling (fueling, saving and loading of fuel per ATC ID) needs to be tested.

Negatives:
N/A

Testing Results: 
Passed

Conclusions: 
Works as expected

Media:
N/A

2024-04-11 09:34 UTC, merged