fix(AOC): prevent early clearing of OOOI-Data #8369
flybywiresim/aircraft pull request #8665
Opened 2024-05-27 18:55 UTC by cptnuss-ops

Fixes #8369 

## Summary of Changes

## Screenshots (if necessary)

## References

## Additional context

Discord username (if different from GitHub):

## Testing instructions

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

2024-06-15 04:31 UTC, Benjozork approved these changes

2024-07-01 17:54 UTC, alepouna commented
Hey heads up, you have conflicting files 🙌

2024-07-01 19:04 UTC, cptnuss-ops commented
> Hey heads up, you have conflicting files 🙌

Sorry, my bad. I resolved the conflict.

2024-07-01 19:21 UTC, alepouna commented
No worries what so ever, thank you for quick patch, I will add RTT labels so it can get QA'd!

2024-07-06 10:07 UTC, noonebling commented
Quality Assurance Trainee Report

Discord          : noonebling
Object of testing: 8665
Tier of Testing  : 1
Date             : 06/07/2024

Testing Process: 
1. Loaded up flight, took off and landed
2. Shutdown at gate and checked OOOI times
3. Prepped next flight and pushbacked to init new cycle
4. Checked if OOOI times are cleared and new leg is started



Negatives:
N/A

Testing Results: 
Passed

Conclusions: 
Works as expected

2024-07-10 20:14 UTC, Maximilian-Reuter requested changes

2024-07-10 20:14 UTC, Maximilian-Reuter commented on fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_ATSU.js
> +const insertUplink = (mcdu) => {
This code seems to be from a bad merge or something. As that code has now all be relocated to typescript.
I think you will have to redo your changes on a branch that is clean from master. 

Simbrief uplink is now all happening here: https://github.com/flybywiresim/aircraft/blob/2cdf866fb140b72151c25e2413dd5365364ba08f/fbw-a32nx/src/systems/fmgc/src/flightplanning/new/uplink/SimBriefUplinkAdapter.ts#L115

2024-07-11 05:11 UTC, cptnuss-ops commented
Ok, I'll close this PR and start again with a fresh codebase.

2024-07-11 05:11 UTC, closed without merging