fix(gear): A380 body gear small door
flybywiresim/aircraft pull request #8794
Opened 2024-08-02 17:11 UTC by crocket63

Fixes #[issue_no]

## Summary of Changes

Placeholder to control small body gear door while gear system is not implemented yet
Note the cinematic is not correct yet as we'd need new gear system state flow, however avoids door closing through extended gear

## Screenshots (if necessary)

## References

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Check gear cinematic. 
Small door should open at gear downlock and stay opened while gear is down.
Door should not open in gravity landing mode.

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

2024-08-20 03:13 UTC, 2hwk requested changes

2024-08-20 03:13 UTC, 2hwk commented on fbw-a380x/src/wasm/systems/a380_systems/src/hydraulic/gear_secondary_doors.rs
> +            }
```suggestion
           self.position += if should_open {
                delta_position
            } else {
                -delta_position
            };
```

2024-08-20 18:12 UTC, Gurgel100 requested changes

2024-08-20 18:12 UTC, Gurgel100 commented on fbw-a380x/src/wasm/systems/a380_systems/src/hydraulic/gear_secondary_doors.rs
> +        );
Remove before merge.

2024-09-14 13:30 UTC, Gurgel100 approved these changes

2024-09-14 13:31 UTC, merged