fix(fms): remove forced turn on following leg after leg insertion
flybywiresim/aircraft pull request #8841
Opened 2024-08-25 10:05 UTC by BlueberryKing

Fixes #[issue_no]

## Summary of Changes

Fixes a few issues with flight plan modifications:
1. After deleting a discontinuity, it could happen that the turn of the new leg went the wrong way due to the leg constellation. This is fixes by creating a TF leg from the leg after the discontinuity.
2. After truncating the flight plan by insertion of an existing waypoint or using DIR to, the outbound turn would sometimes go the wrong way because the following leg was coded with a forced turn. This is fixed by removing the forced turn on the following leg.

## Screenshots (if necessary)

Before: 
![image](https://cdn.discordapp.com/attachments/1277032019540316212/1277032020433965146/Screenshot_2024-08-24_215701.png?ex=66cbb03f&is=66ca5ebf&hm=a44db70a705dcdfddbd200516887b807fd6fabdc8a739372a3c7969c85ca9f08&)
After:
![image](https://github.com/user-attachments/assets/98cf21ed-2c31-4568-bd87-66f2fa2fd7a9)

Before:
![image](https://media.discordapp.net/attachments/748096886531162123/1251427705895784509/image3.png?ex=66cc24df&is=66cad35f&hm=8b897eea1bbced9ed1d5b1521125b89341a4ea0d34e2ac33dbf7c5330ea4f3b9&=&format=webp&quality=lossless)
After:
![image](https://github.com/user-attachments/assets/44318004-bb4e-4406-ae3e-0b655c5fc6ca)

## References

## Additional context

Discord username (if different from GitHub):

## Testing instructions

- Fly a procedure with a forced turn, try going DIR to the leg with the forced turn (indicated by a left/right arrow in the FPLN page). Make sure the turn goes the wrong way.
- Clear discontinuities on procedures. Make sure all turns go the right way.

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

2024-08-25 14:22 UTC, Benjozork requested changes

2024-08-25 14:22 UTC, Benjozork commented on fbw-a32nx/src/systems/fmgc/src/flightplanning/plans/BaseFlightPlan.ts
> +              nextSegment.allLegs.splice(nextIndexInSegment, 1, newNextElement);
If we modify segments other than the one the leg being removed is in, we should add a sync call for that segment at the end of this function.

2024-08-25 14:22 UTC, Benjozork commented on fbw-a32nx/src/systems/fmgc/src/flightplanning/plans/BaseFlightPlan.ts
> +  protected removeForcedTurnAt(index: number) {
Needs sync

2024-08-25 20:04 UTC, tracernz approved these changes

2024-08-27 14:36 UTC, Benjozork approved these changes

2024-08-27 18:32 UTC, pilotseyea350 commented
Quality Assurance Trainee Report

Discord: PilotEyesA350
Object of testing: #8841
Tier of Testing: 2
Date: 27/08/2024

Testing Process:

- Load into EGKK RWY26R
- Use EGKK/EGKK in INIT A
- Select ILS26L, VASU1G via WILLO for arrival at EGKK
- Verify Left Arrow at HOLLY and WILLO
- Select HOLLY as TMPY DIR TO
- Verify TMPY turn is quickest way to next Waypoint
- Delete TMPY DIR TO
- Select WILLO as TMPY DIR TO
- 
Negatives:
DIR TO HOLLY works as expected, however DIR TO WILLO creates a weird artifact on ND

Testing Results:
Not Passed

Conclusions:
Not passed

Media:
![Capture d'écran 2024-08-27 124408](https://github.com/user-attachments/assets/c11141c8-6131-43b5-afe3-f956b0e1a991)

2024-10-27 14:50 UTC, tracernz commented
Needs 0.13 changelog.

2025-02-11 19:49 UTC, alexr4339 commented
<!-- !! DO NOT REMOVE THIS LINE !! - QUALITY ASSURANCE REPORT -->
<!-- Refer to the https://docs.flybywiresim.com/dev-corner/qa-process/#reporting-on-tests for details about this template -->

<!-- Please use one or the other depending on your Discord Role -->
Quality Assurance Tester/Trainee Report

Discord Username  : alexdnzdmb <!-- Use your username, not your display name! -->
Object of testing : #8841  <!-- PR Number -->
Aircraft          : A32NX <!-- Choose only one -->
Tier of Testing   : 2
Date              : 11/02/2025 <!-- Date of test in DD/MM/YYYY format -->

Testing Process: 
Tested multiple procedures
Performed DTO's and verified turn didnt follow forced turn of waypoint but followed the shortest route towards next waypoint
Performed deletions of Discos and verified a direct connection between the two waypoints

Testing Results: 
Passed

2025-02-12 18:54 UTC, merged