fix(lgciu): Adds wing weight on wheels sensors on 380X
flybywiresim/aircraft pull request #9020
Opened 2024-10-04 09:46 UTC by crocket63

Fixes #[issue_no]

## Summary of Changes

Fixes issue where plane will have main gears on ground only from body gear info.
This is a placeholder waiting for correct 380X gear implementation 

## Screenshots (if necessary)

## References

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Non regression on 32NX: check weight on wheels dependent logic/ ground spoilers / gear retraction extension
380 should have LGCIU variables on ground if wing OR body gear on considered side is compressed

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

2024-10-04 12:06 UTC, aguther requested changes
LGTM with the small request to update the comment.

2024-10-04 12:06 UTC, aguther commented on fbw-common/src/wasm/systems/systems/src/landing_gear/mod.rs
>      // Is extended at 0.5, we set a super small margin of 0.02 from fully extended so 0.52
This comment should be updated to reflect the new variables and values.

2024-10-08 02:46 UTC, Popespice commented
<!-- !! DO NOT REMOVE THIS LINE !! - QUALITY ASSURANCE REPORT -->
<!-- Refer to the https://docs.flybywiresim.com/dev-corner/qa-process/#reporting-on-tests for details about this template -->

<!-- Please use one or the other depending on your Discord Role -->
Quality Assurance Tester Report

Discord Username  : popespice
Object of testing : #9020 
Aircraft          : A32NX
Tier of Testing   : 2
Date              : 07/10/2024

Testing Process: 
1. Load plane as usual
2. Take off
3. Do a circuit of SF bay
4. Arm spoilers as normal
5. Come back to land
6. Observe that on landing spoilers deploy; observe that before takeoff gear will not go up

Testing Results: 
Passed 

Negatives:       

Conclusions: 
Working as expected

2024-10-08 16:44 UTC, aguther approved these changes

2024-10-08 20:28 UTC, merged