fix(a380x/fcu) altitude and baro instruments should show values during light test
flybywiresim/aircraft pull request #9165
Opened 2024-10-28 12:37 UTC by mattgogerly

Fixes #[9092]

## Summary of Changes

The OverheadPublisher was not being instantiated anywhere, so the subscription in the Baro/Altitude components was never receiving any events.

## Screenshots (if necessary)

Pending model release...

## References

See issue for pictures

## Additional context

Discord username (if different from GitHub): nothematic

## Testing instructions

1. Load into the sim & power on
2. Press light test switch
3. Altitude and baro instruments should display "8" values

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

2024-10-28 20:40 UTC, tracernz approved these changes

2024-10-29 15:14 UTC, alepouna commented
Needs changelog conflict fix and lgtm

2024-10-29 15:16 UTC, 2hwk commented
You should get the contributor role on our discord shortly, thank you for your first contribution to the repository.

2024-10-29 15:42 UTC, mattgogerly commented
> You should get the contributor role on our discord shortly, thank you for your first contribution to the repository.

Do you want me to fix the changelog conflict or will a bot magically do it?

2024-10-29 15:55 UTC, alepouna commented
> > You should get the contributor role on our discord shortly, thank you for your first contribution to the repository.
> 
> Do you want me to fix the changelog conflict or will a bot magically do it?

No bot yet to handle that, needs to be done by you! 🙌

2024-10-29 15:56 UTC, alepouna requested changes

2024-10-29 15:56 UTC, alepouna commented on .github/CHANGELOG.md
> +1. [FCU] Fixed auto-initialisation of baro unit - @tracernz (Mike)
```suggestion
```
Duplicate

2024-10-30 03:16 UTC, alepouna approved these changes

2024-10-30 04:40 UTC, merged