fix(EFB): Agnostic opt in to error reporting
flybywiresim/aircraft pull request #9257
Opened 2024-11-01 06:53 UTC by sschiphorst

Fixes #[issue_no]

## Summary of Changes

Change error reporting popup to be plane agnostic rather than just A32NX

## Screenshots (if necessary)

## References

## Additional context

Discord username (if different from GitHub): Yahtzee94

## Testing instructions

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

2024-11-02 01:54 UTC, 2hwk approved these changes

2024-11-02 01:55 UTC, 2hwk requested changes

2024-11-02 01:55 UTC, 2hwk commented on fbw-common/src/systems/shared/src/FbwAircraftSentryClient.ts
> +      popup.showPopUp( /
```suggestion
      popup.showPopUp(
```

The `/` character is causing the build to fail. Remove to correct the syntax please.

2024-11-02 06:33 UTC, sschiphorst reviewed
Have amended

2024-11-02 06:41 UTC, tracernz approved these changes

2024-11-04 07:57 UTC, 2hwk approved these changes

2024-11-04 09:33 UTC, tracernz commented on fbw-common/src/systems/shared/src/FbwAircraftSentryClient.ts
> +      popup.showPopUp(
You've added a trailing space here. The lint won't like that.

2024-11-14 15:27 UTC, 2hwk approved these changes

2024-11-15 11:06 UTC, 2hwk commented
<!-- !! DO NOT REMOVE THIS LINE !! - QUALITY ASSURANCE REPORT -->
<!-- Refer to the https://docs.flybywiresim.com/dev-corner/qa-process/#reporting-on-tests for details about this template -->

<!-- Please use one or the other depending on your Discord Role -->
Quality Assurance Tester Report

Discord Username: 2cas
Object of testing: #9257
Aircraft:  A380X
Tier of Testing: 1
Date: 15/11/2024 

Testing Process: 
- [x] Launch either aircraft at stand or runway
- [x] Power on EFB
- [x] In settings go to ATSU/AOC
- [x] Toggle errror reporting on
- [x] Confirm correct message appears

Testing Results: 
QA Passed

Negatives:       
- N/A

Conclusions: 
- LGTM

2024-11-16 08:45 UTC, merged