feat(a380x/flex): Wing flex tuning
flybywiresim/aircraft pull request #9424
Opened 2024-11-06 11:49 UTC by crocket63

Fixes #[issue_no]

## Summary of Changes

Trying to add a bit more flexibility while keeping flex under control at min or max fuel load.

## Screenshots (if necessary)

## References

## Additional context

Discord username (if different from GitHub):

## Testing instructions

This is mainly a "feeling check" and trying to cross check with any YouTube reference:

Check against any findable reference that full fuel load gives correct wing flex on ground. Same for empty of fuel.
Check against any findable reference that wing bend looks correct from same window views as real life references
Check that wing flex do not go crazy on hard landings.
Check that smooth landing gives correct flex oscillations
Check that wing drops with ground spoiler deployed 

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

2024-11-08 01:27 UTC, 2hwk approved these changes

2024-11-08 01:29 UTC, 2hwk requested changes

2024-11-08 01:29 UTC, 2hwk commented on .github/CHANGELOG.md
> +1. [A380/WingFlex] Reduced stiffness of wings for more tip up bend - @Crocket63 (crocket)
```suggestion
1. [A380/WING_FLEX] Reduced stiffness of wings for more tip up bend - @Crocket63 (crocket)
```

2024-11-08 01:29 UTC, 2hwk commented on .github/CHANGELOG.md
> +1. [A380/WingFlex] Reduced stiffness of wings for more tip up bend - @Crocket63 (crocket)
Just a minor consistency change for changelog, no code change affected.

2024-11-08 04:12 UTC, AlonsoJCY commented
I can give a evidence for you to check. Hope it is helpful :)
![Comp wing flex](https://github.com/user-attachments/assets/839cd1d1-3bbc-4796-8283-2a82367f5e15)
LHS is simulator; RHS is IRL.
LHS from PVG to PEK; RHS from PVG to FRA
Even if the fuel load on the RHS is greater than on the LHS, RHS still has more wing flex.

2024-11-08 17:16 UTC, A359Flex commented
Any way to modify or change this tuning as per the user's desire in case if he needs to do it by himself?

2024-11-08 21:17 UTC, A359Flex commented
> > Any way to modify or change this tuning as per the user's desire in case if he needs to do it by himself?
> 
> Well flex is not user desire based, it's physics... So answer is: if one find references with good amount of information that can give insights to improve the tuning, then anyone can propose a new tuning in here, it's open source.
> 
> But having a wing flex setting in EFB would be non sense to me.
> 
> Also lot of possible improvement in the dynamic would need Asobo changes. Feel free to upvote this request: https://devsupport.flightsimulator.com/t/can-we-access-surfaces-lift-values/5574?u=davy63000

Fine, but what I've noticed was that despite increasing gross weights and during conditions of high pitch attitudes, the wing remained relatively stiff which isn't anything like it behaves in real life where the deflection of the outer 2/3rds does vary with the above-mentioned factors. 
<img width="1280" alt="Microsoft Flight Simulator Screenshot 2024 10 30 - 14 18 11 79" src="https://github.com/user-attachments/assets/92a4b646-8748-4834-b87f-00e5555b68e5">
![A380-Emirates-Golf-Oscar-Romeo](https://github.com/user-attachments/assets/38ceca59-ff79-4bc8-8634-aaf3ad2f6a86)
![shutterstock_112881910-1](https://github.com/user-attachments/assets/2561805a-762b-4250-80e8-fe5a26f38271)

2024-11-09 19:35 UTC, A359Flex commented
> > > > Any way to modify or change this tuning as per the user's desire in case if he needs to do it by himself?
> > 
> > 
> > > 
> > 
> > 
> > > Well flex is not user desire based, it's physics... So answer is: if one find references with good amount of information that can give insights to improve the tuning, then anyone can propose a new tuning in here, it's open source.
> > 
> > 
> > > 
> > 
> > 
> > > But having a wing flex setting in EFB would be non sense to me.
> > 
> > 
> > > 
> > 
> > 
> > > Also lot of possible improvement in the dynamic would need Asobo changes. Feel free to upvote this request: https://devsupport.flightsimulator.com/t/can-we-access-surfaces-lift-values/5574?u=davy63000
> > 
> > 
> > Fine, but what I've noticed was that despite increasing gross weights and during conditions of high pitch attitudes, the wing remained relatively stiff which isn't anything like it behaves in real life where the deflection of the outer 2/3rds does vary with the above-mentioned factors.
> > <img alt="Microsoft Flight Simulator Screenshot 2024 10 30 - 14 18 11 79" width="1280" src="https://private-user-images.githubusercontent.com/187149123/384526943-92a4b646-8748-4834-b87f-00e5555b68e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExODA5OTQsIm5iZiI6MTczMTE4MDY5NCwicGF0aCI6Ii8xODcxNDkxMjMvMzg0NTI2OTQzLTkyYTRiNjQ2LTg3NDgtNDgzNC1iODdmLTAwZTU1NTViNjhlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQxOTMxMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTI0MTFjMzY4NTY2MzkwYmVhNDI5YzBhZTA2OTIzNDkwZDdkYzM3MjE2ZDkzZjdkNmI4ZTgwMTNlNmVlMzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1cBzyHCKF3YFc0xXvmf2QkEjMrZdzbhazxz7vbtV4tY">
> > ![A380-Emirates-Golf-Oscar-Romeo](https://private-user-images.githubusercontent.com/187149123/384527015-38ceca59-ff79-4bc8-8634-aaf3ad2f6a86.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExODA5OTQsIm5iZiI6MTczMTE4MDY5NCwicGF0aCI6Ii8xODcxNDkxMjMvMzg0NTI3MDE1LTM4Y2VjYTU5LWZmNzktNGJjOC04NjM0LWFhZjNhZDJmNmE4Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQxOTMxMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OTY2MWYzYmM2YmMyNWFjMGQ5YWY5ZDRiOWI1YzhmNmZmOTI5Y2M1ZTNjNWMxZmNlNWQxOGI4MDIyZGU5ZjVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.humyl7eqNQSR8eMQaRl2vCbkFAK6aaF4AwLzT8ofvM4)
> > ![shutterstock_112881910-1](https://private-user-images.githubusercontent.com/187149123/384527076-2561805a-762b-4250-80e8-fe5a26f38271.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExODA5OTQsIm5iZiI6MTczMTE4MDY5NCwicGF0aCI6Ii8xODcxNDkxMjMvMzg0NTI3MDc2LTI1NjE4MDVhLTc2MmItNDI1MC04MGU4LWZlNWEyNmYzODI3MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQxOTMxMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MGI0NDRjOTEzM2I4NWNlZmIzMGJmOGQ5Mzk3NDlkNTcyN2FiOWVjMGZkODViOGZmM2Y5NWYzOWMxYjc2NTVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.R-outrbq6XkAGEctS0mhpAA8lkAxtU1CgAI_odS3G2M)
> 
> For example you don't have same angle at all on the first two so can't compare anything. Other example, this is without the tuning in this PR: ![image](https://private-user-images.githubusercontent.com/38904654/384596778-bb7408b3-f5a4-4082-bbea-4c3c48be37a2.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExODA5OTQsIm5iZiI6MTczMTE4MDY5NCwicGF0aCI6Ii8zODkwNDY1NC8zODQ1OTY3NzgtYmI3NDA4YjMtZjVhNC00MDgyLWJiZWEtNGMzYzQ4YmUzN2EyLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQxOTMxMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTg2Y2E5ZTg3NDJlZjNlNjQ3NzY3ODE4MTcyMmY2MGY0ZDgzZDhiMzExMDBmMjJhNzE5NDQ0MDA1Zjk4YmIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lSxUMGte5d9Sx4dzs6ar_QiUz6fOdKCwloMj8jWtiiI)

It is impossible to get the two very exact same angles in space and time so that argument is moot as long as there is closeness and even in your screenshot the outboard wing shows slightly more deflection. And there's plenty of evidence that the FBW A380X right now does not exhibit sufficient flexing behaviour as seen in the real aircraft.
![382172406-a3e576a3-f2f7-41b9-ae50-633f4e3b5591](https://github.com/user-attachments/assets/4f5c072c-8f12-4fa8-947c-55525a84672b)
<img width="1280" alt="Microsoft Flight Simulator Screenshot 2024 11 02 - 08 13 12 100" src="https://github.com/user-attachments/assets/081a4b84-d8f0-45f5-805f-437c493aeda9">
![382957844-b5bebfe3-2baf-4416-b658-0800bc8e257a](https://github.com/user-attachments/assets/023b9e8f-0ec3-4c52-904e-21c0daf4c55f)

2024-11-09 19:38 UTC, Benjozork commented
There are so many pictures and quotes of pictures that it's getting hard to see messages strictly related to the PR. I suggest you continue this conversation on Discord.

2024-11-10 10:45 UTC, 2hwk approved these changes

2024-11-10 10:48 UTC, alepouna commented
Reminder for observers of this PR, that for flex comparisons with our aircraft and the IRL a380, we need additional data such as the weight, fuel and the "POVs" to match in both comparisons, otherwise it isn't really helpful!

2024-11-10 12:02 UTC, beheh commented
I think the "Needs Accuracy Check" label here is mostly moot. It makes sense for systems that can be looked up or tested and compared 1:1, but wing flex, like graphical choices such as textures or lighting, are always going to be somewhat subjective.

2024-11-10 13:50 UTC, 2hwk commented
<!-- !! DO NOT REMOVE THIS LINE !! - QUALITY ASSURANCE REPORT -->
<!-- Refer to the https://docs.flybywiresim.com/dev-corner/qa-process/#reporting-on-tests for details about this template -->

<!-- Please use one or the other depending on your Discord Role -->
Quality Assurance Report

Discord Username: 2cas<!-- Use your username, not your display name! -->
Object of testing: #9424<!-- PR Number -->
Aircraft: A380X <!-- Choose only one -->
Tier of Testing: 1
Date: 10/11/2024 <!-- Date of test in DD/MM/YYYY format -->

Testing Process: 
<!-- List the process - Required section --> 
- [x] Check against any findable reference that full fuel load gives correct wing flex on ground. Same for empty of fuel.
   - Compared to gate photos of known routes and fuel levels
- [x] Check against any findable reference that wing bend looks correct from same window views as real life references
   - Compared to videos of known fuel levels, historical conditions, etc.
- [x] Check that wing flex do not go crazy on hard landings.
  - Slammed it and bounced on purpose, used slew mode to throw the plane into the runway. Wing flex does not break.
- [x] Check that wing drops with ground spoiler deployed

Testing Results: 
QA Passed <!-- Required section --> 

Negatives:       
<!-- Ommit this section if none are found -->
-  Same issue as before during takeoff rollout (due to not having the sim flight model calculation's actual wing lift values.
  - i.e. wing does not lift before rotation, then snaps into place, that limitation still exists.

Conclusions: 
<!-- Ommit section if nothing to add -->
- There is more perceived wing flex, still the same issue as before during takeoff rollout (due to not having the sim flight model calculation's actual wing lift values.

2024-11-11 02:17 UTC, 2hwk commented
> > Quality Assurance Report
> > Discord Username: 2cas Object of testing: #9424 Aircraft: A380X Tier of Testing: 1 Date: 10/11/2024
> > Testing Process:
> > 
> > * [x]   Check against any findable reference that full fuel load gives correct wing flex on ground. Same for empty of fuel.
> >   
> >   * Compared to gate photos of known routes and fuel levels
> > * [x]   Check against any findable reference that wing bend looks correct from same window views as real life references
> >   
> >   * Compared to videos of known fuel levels, historical conditions, etc.
> > * [x]   Check that wing flex do not go crazy on hard landings.
> >   
> >   * Slammed it and bounced on purpose, used slew mode to throw the plane into the runway. Wing flex does not break.
> > * [x]   Check that wing drops with ground spoiler deployed
> > 
> > Testing Results: QA Passed
> > Negatives:
> > 
> > * Same issue as before during takeoff rollout (due to not having the sim flight model calculation's actual wing lift values.
> > * i.e. wing does not lift before rotation, then snaps into place, that limitation still exists.
> > 
> > Conclusions:
> > 
> > * There is more perceived wing flex, still the same issue as before during takeoff rollout (due to not having the sim flight model calculation's actual wing lift values.
> 
> Mmmmm I'm now blending ground and air mode slowly so it should to some extent raise during the to roll even if last bit happens at lift off ? At rotation you also get AoA so it's expected to have a bit of flex punch there though.

There was some rise towards the end of the TO roll but it does seem slightly delayed. Good enough to merge into master as it is better than before.

2024-11-11 03:11 UTC, merged