fix(a380x/mfd): Accept 0°C temperature values
flybywiresim/aircraft pull request #9425
Opened 2024-11-06 13:36 UTC by FDM-Tech

Fixes #[issue_no]

## Summary of Changes

## Screenshots (if necessary)

## References

## Additional context

Discord username (if different from GitHub):

## Testing instructions

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

2024-11-07 05:28 UTC, beheh requested changes
Thanks for your contribution. 

However, have you tested this? The changes didn't really make much sense to me as they only apply when the parsed number is larger than 0.

As part of the PR please also fill out the template, especially with proper test instructions.

2024-11-07 05:28 UTC, beheh commented on fbw-a380x/src/systems/instruments/src/MFD/pages/common/DataEntryFormats.tsx
> +    if (nbr > 0 && input.substring(0, 1) !== '+') {
This doesn't seem to make much sense. This will make everything negative unless you explicitly prefix with +.

2024-11-07 05:28 UTC, beheh commented on fbw-a380x/src/systems/instruments/src/MFD/pages/common/DataEntryFormats.tsx
> +      nbr = input.substring(1);
I don't understand what this is trying to do. At this point nbr has already successfully been parsed, and you're now replacing it with a string (without parsing).

2024-11-10 11:01 UTC, alepouna commented
Please fill the PR template as BehEh mentioned - remove Invalid after filled.

2025-11-24 07:13 UTC, closed without merging