feat: initial commit
flybywiresim/aircraft pull request #9471
Opened 2024-11-10 00:08 UTC by Benjozork

Fixes #[issue_no]

## Summary of Changes

## Screenshots (if necessary)

## References

## Additional context

Discord username (if different from GitHub):

## Testing instructions

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

2024-11-12 10:24 UTC, FDM-Tech commented
Please merge this pull request if possible @flogross89

2024-11-12 16:13 UTC, Benjozork commented
It'll be merged when it's ready.

2025-01-02 21:33 UTC, tracernz requested changes

2025-01-02 21:33 UTC, tracernz commented on fbw-a32nx/src/systems/fmgc/src/efis/EfisSymbols.ts
> +          radii: fixInfo?.radii.map((it) => it.radius),
fixInfo cannot be nullish here.
```suggestion
          radials: fixInfo.radials.map((it) => it.trueBearing),
          radii: fixInfo.radii.map((it) => it.radius),
```

2025-01-02 21:33 UTC, tracernz commented on fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/F-PLN/MfdFmsFplnFixInfo.tsx
> +import './MfdFmsFplnFixInfo.scss';
Move to top or bottom of import list.

2025-01-02 21:33 UTC, tracernz commented on fbw-common/src/systems/navdata/shared/types/BaseFix.ts
> +export type AnyFix = BaseFix<SectionCode>;
This feels like a bit of a hack given we already have a Fix type that is supposed to be any fix. Is there any reason Fix can't just be this type? Alternately, if you just want the location prop then we probably just want a LocationInterface or something like that.

2025-01-02 21:50 UTC, Benjozork commented on fbw-common/src/systems/navdata/shared/types/BaseFix.ts
> +export type AnyFix = BaseFix<SectionCode>;
I believe this was so airports worked here.

2025-01-04 16:19 UTC, Benjozork commented on fbw-common/src/systems/navdata/shared/types/BaseFix.ts
> +export type AnyFix = BaseFix<SectionCode>;
Do you have something in mind that would be more appropriate?

2025-01-04 16:38 UTC, Ueeew commented on fbw-common/src/systems/navdata/shared/types/BaseFix.ts
> +export type AnyFix = BaseFix<SectionCode>;
@Benjozork I just so your PR and I want to test it but I noticed thats a bit out of date now, so I have just a small request: could you just merge the "master" file again into your pull-request so thats up-to-date again. That would be great. Thanks

2025-01-04 16:38 UTC, Ueeew commented
@Benjozork I just so your PR and I want to test it but I noticed thats a bit out of date now, so I have just a small request: could you just merge the "master" file again into your pull-request so thats up-to-date again. That would be great. Thanks

2025-01-05 01:38 UTC, Benjozork commented on fbw-a32nx/src/systems/fmgc/src/efis/EfisSymbols.ts
> +          radii: fixInfo?.radii.map((it) => it.radius),
Fixed

2025-01-05 01:38 UTC, Benjozork commented on fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/F-PLN/MfdFmsFplnFixInfo.tsx
> +import './MfdFmsFplnFixInfo.scss';
Fixed

2025-01-05 01:45 UTC, tracernz commented on fbw-common/src/systems/navdata/shared/types/BaseFix.ts
> +export type AnyFix = BaseFix<SectionCode>;
No, was hoping you would 😁 . We can revisit the design here some other time; this wasn't the comment I was requesting mandatory changes for.

2025-01-05 21:20 UTC, Ueeew commented
@Benjozork If tested, and firstly, I want to say thank you for your work. It works good, and it is really nice to have a fix-info page now. There are just a few small bugs I found. The first thing I found is that I was not able to delete fixes I entered previously in the flight. The second bug is that the Fix 4 doesn't work; the things you enter there are not getting displayed. But beside these bugs, it's really good. And at the end, I have a small request. I don't know if this has to do with the fix info, but could you add the option to enter your own waypoints and airports? Thank you for all your work. :)

2025-01-06 03:18 UTC, Rocket-Nerd commented
<!-- !! DO NOT REMOVE THIS LINE !! - QUALITY ASSURANCE REPORT -->
<!-- Refer to the https://docs.flybywiresim.com/dev-corner/qa-process/#reporting-on-tests for details about this template -->

<!-- Please use one or the other depending on your Discord Role -->
External QA Report

Discord Username  : rocketnerd <!-- Use your username, not your display name! -->
Object of testing : #9471 <!-- PR Number -->
Aircraft          : A380X <!-- Choose only one -->
Tier of Testing   : 1/2
Date              : 4/1/2025 <!-- Date of test in DD/MM/YYYY format -->

Testing Process:
<!-- List the process - Required section -->
1. Started up AC from cold and dark
2. Loaded the KSFO quiet bridge visual using PDBs as shown in the testing instructions
3. Used fix info to display the 095 radial from the SFO VOR, made sure it aligned with the PBDs for the approach
4. Created fix info for the ARCHI waypoint, made sure it aligned with the path to first PBD on the approach as per the charts
5. Created fix info for the KSFO28R
6. Checked to make sure fixed synced across FMS 1 and 2

Testing Results:
Passed <!-- Required section -->

Negatives:
1. Fix info does not load until the return button is pressed
2. Cannot remove a radial from a given fix, only can be done by renaming the fix which resets all radials/radius
<!-- Ommit this section if none are found -->

Media:
![image46](https://github.com/user-attachments/assets/589a5de5-c6d4-4f42-b3ab-cd7425542f6c)
![image45](https://github.com/user-attachments/assets/e411b4a2-c989-449c-9de6-fcf5d30bdd11)

2025-01-20 21:48 UTC, BravoMike99 commented
<!-- !! DO NOT REMOVE THIS LINE !! - QUALITY ASSURANCE REPORT -->
Quality Assurance Tester Report

Discord Username  : bruno_pt99
Object of testing : #9471  
Aircraft          : A32NX 
Tier of Testing   : 1
Date              : 20/01/2025 

Testing Process: 
Test fix info still works correctly on A32NX ❌ 

Testing Results: 
Not Passed

Negatives:       
FIX INFO radials & radius only update on the A32NX after changing the range or mode of the ND. On the A380X it works fine.

Media:
![image](https://github.com/user-attachments/assets/5db565b2-4e7e-4df5-a2f2-40031d7c52f0)

2025-01-21 00:10 UTC, tracernz commented on fbw-common/src/systems/navdata/shared/types/BaseFix.ts
> +export type AnyFix = BaseFix<SectionCode>;
Yes. https://github.com/flybywiresim/aircraft/pull/9792

2025-01-27 21:52 UTC, BravoMike99 commented
<!-- !! DO NOT REMOVE THIS LINE !! - QUALITY ASSURANCE REPORT -->

Dev team QA report

Discord Username  : bruno_pt99 
Object of testing : #9471
Aircraft          : A32NX & A380X 
Tier of Testing   : 1 
Date              : 27/01/2025 

Testing Process: 
Inserted fix info data for runways, navaids, waypoints & airports and checked it works correctly ✔️ 
Changed MFD pages and observed Fix info data remains stable and is updated accordingly on both MFDs & NDs upon insertion, deleting & updating ✔️ 
Manually coded the LPPT 20 FTM6S  departure using PBDs, and verified the fix info radials coincide with the PBDs ✔️ .
Checked A320 FIX info works correctly, by the same testing as above ✔️ 

Testing Results: 
Passed


Media:
![image](https://github.com/user-attachments/assets/e08e9ead-1ba3-4d69-ab5f-c7168a9e9850)
![Fix2A380](https://github.com/user-attachments/assets/924e1f3a-f323-430c-b4a1-3968fe0cf280)
![FixA3801](https://github.com/user-attachments/assets/e9f80836-532d-4431-9140-6cf70a26c603)
![Fix2](https://github.com/user-attachments/assets/c158ad37-9c53-4b3c-8fa9-29bd604dbc06)
![Fix1](https://github.com/user-attachments/assets/1de2cc1e-3b21-496e-bac1-1817989e14de)

2025-02-01 13:41 UTC, heclak commented
@Benjozork not sure if you've realised that the auto-merge isn't working due to a failed lint & test.

2025-02-01 16:08 UTC, Benjozork commented
I hadn't... thanks.

2025-02-01 16:56 UTC, merged