fix(a380/mfd): Various Fixes in fuel & load page
flybywiresim/aircraft pull request #9540
Opened 2024-11-16 19:32 UTC by BravoMike99

Fixes #9342 

## Summary of Changes

Fixes destination ETA being displayed in local time and not UTC time.
Adds flight time prediction to MFD during preflight phase.
Fixes trip fuel (non preflight) & trip time missing.
Fixes FOB value on the top of the page. 
Enables RTE RSV & absolute value input fields.
Updates AMI defaults for A380 (taxi fuel & reserve max)

## Screenshots (if necessary)

![PreFlight](https://github.com/user-attachments/assets/09924989-9dd4-4057-801e-8c0052f74449)
![FuelLoad3](https://github.com/user-attachments/assets/54904694-1781-4732-abe3-a256b2f6376d)
![RTE RSV2](https://github.com/user-attachments/assets/2cd203dd-dc18-4fd5-9276-3f32a7c2b8af)
![RTE RSV](https://github.com/user-attachments/assets/7b060b0b-c2a6-4b0d-ac8d-6512b083fa3a)

## References

## Additional context

Discord username (if different from GitHub):
bruno_pt99
## Testing instructions

Start the airplane with engines off and program a flight plan.
Fill the FUEL & Load page during preflight:
1) "TIME" should be displayed on the bottom of the page above the destination airport and the estimate shows the expected flight time.
2) Trip time should be visible next to the trip fuel value
3) Enter an absolute value in the RTE RSV field. The percentage field should become dashed. Once the deleted, the percentage value appears with a value of 5% and the absolute value corresponds to that percentage of the trip fuel.
4) Change the percentage manually and verify that the absolute value is recalculated based on the entered percentage.

Perform a normal takeoff & observe the fuel & load page once in the air:
1) RTE RSV fields should show 0.0.
2) Prediction at the bottom of the page to the destination is now in ETA rather than flight time & header shows "UTC"
3) FOB value matches what is sensed by the aircraft on the top of the page
4) Trip fuel (Expected fuel required between present time ) & trip time (remaining flight time) fields are filled with data and are in line with the FMS predictions .
5) Extra fuel field corresponds to Destination EFOB - MIN DEST FUEL.

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

2024-11-17 02:22 UTC, 2hwk requested changes

2024-11-17 02:22 UTC, 2hwk commented on fbw-a380x/src/systems/instruments/src/MFD/shared/utils.ts
> +  if (seconds === null || seconds === undefined) {
```suggestion
  if (!seconds && seconds !== 0) {
```

May also be useful to check for `NaN` and `""`

2024-11-17 02:23 UTC, 2hwk commented on fbw-a380x/src/systems/instruments/src/MFD/shared/utils.ts
> +  if (seconds === null || seconds === undefined) {
Or perhaps gracefully handle these cases and error log it as these should never be thrown.

2024-11-21 16:04 UTC, 2hwk approved these changes

2024-12-10 09:07 UTC, heclak commented
@BravoMike99 do you need help testing this? There are some conflicts blocking the build.

2024-12-28 09:17 UTC, tracernz commented
You can probably make a better summary in the title by removing the redundant “fixes”. The title is what we will see after this is squash merged.

2025-01-12 10:27 UTC, Jaronics commented
<!-- !! DO NOT REMOVE THIS LINE !! - QUALITY ASSURANCE REPORT -->
<!-- Refer to the https://docs.flybywiresim.com/dev-corner/qa-process/#reporting-on-tests for details about this template -->

<!-- Please use one or the other depending on your Discord Role -->
Quality Assurance Trainee Report

Discord Username  : Jaronics <!-- Use your username, not your display name! -->
Object of testing : #9540  <!-- PR Number -->
Aircraft          : A380X <!-- Choose only one -->
Tier of Testing   : 1
Date              : 12/01/2025 <!-- Date of test in DD/MM/YYYY format -->

Testing Process: 

On the ground:
1. Set up the FMC
2. Checked that the route time is displayed correctly
3. RTE RSV field takes absolute value and percentage becomes dashed
4. When inputting a percentage, the RTE RSV gets recalculated properly

In the air:
1. RTE RSV fields are disabled and show 0.0
2. Time at the bottom shows UTC and corresponds with the ETA on the FPLN page
3. FOB value matches with sensed fuel
4. TRIP fuel and time are in line with FMS predictions
5. EXTRA FUEL corresponds to EFOB - MIN DEST FUEL
<!-- List the process - Required section --> 

Testing Results: 
Passed <!-- Required section --> 

Negatives:       
None<!-- Ommit this section if none are found -->

Conclusions: 
None<!-- Ommit section if nothing to add -->

Media:
None<!-- Ommit this section if no media to add -->

2025-01-12 11:14 UTC, merged