fix: engines not starting properly in msfs 2024
flybywiresim/aircraft pull request #9583
Opened 2024-11-24 01:20 UTC by Saschl

Fixes #[issue_no]

## Summary of Changes

execute_calculator_code does not seem to work properly (and is discouraged anyway). Replaced with `trigger_key_event` (deprecated but working in both sims), which brings the correct behaviour back again.

## Screenshots (if necessary)

## References

## Additional context

Discord username (if different from GitHub):

## Testing instructions

1. Spawn C&D in both sims ideally and perform engine starts with APU and ASU. N2 should rise quickly after engine master switches have been turned on

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

2024-11-24 01:48 UTC, tracernz approved these changes

2024-11-24 01:48 UTC, tracernz commented
No changelog needed as there's no user-visible change.

2024-11-24 01:50 UTC, flogross89 commented
Does this only apply to Rust code or also to C++ code? ``execute_calculator_code`` is used extensively there

2024-11-24 02:00 UTC, Saschl commented
> Does this only apply to Rust code or also to C++ code? `execute_calculator_code` is used extensively there

Will need to check that as well 👍 Most of the calls do not seem to take parameters which seems to work fine, but I haven't checked very thoroughly yet

2024-11-24 03:44 UTC, Gurgel100 requested changes

2024-11-24 03:44 UTC, Gurgel100 commented on fbw-common/src/wasm/systems/systems_wasm/src/electrical.rs
> +    trigger_key_event(KEY_APU_BLEED_AIR_SOURCE_SET, action);
```suggestion
    trigger_key_event(KEY_APU_BLEED_AIR_SOURCE_SET, on.into());
```

2024-11-24 10:45 UTC, Saschl commented on fbw-common/src/wasm/systems/systems_wasm/src/electrical.rs
> +    trigger_key_event(KEY_APU_BLEED_AIR_SOURCE_SET, action);
Ohh nice, fixed :)

2024-11-24 23:54 UTC, Gurgel100 approved these changes

2024-11-26 14:14 UTC, denmax18 commented
We have problems with the simbrief tool open all power disconnecting. A388

2024-11-26 15:51 UTC, merged