feat(pfd): add LS reminder indicator
flybywiresim/aircraft pull request #9668
Opened 2024-12-16 22:58 UTC by BravoMike99

Fixes #[issue_no]

## Summary of Changes

## Screenshots (if necessary)

## References

## Additional context

Discord username (if different from GitHub):

## Testing instructions

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

2024-12-18 17:02 UTC, G-DRAW commented
Aircraft Version
Stable

Build info
"v0.12.0"
Describe the bug
When doing an ILS approach in the A380, and the LS P/B's on EFIS is not turned ON, the LS will constantly flash in amber which is correct, but doesn't automatically display the lateral and vertical deviation scales when LOC or APPR Mode is armed.

Expected behavior
If LS P/B isn't selected when doing an ILS approach, it would automatically display the LOC and G/S deviation scales on both PFD's after arming the LOC P/B or APPR P/B, and the LS P/B's would automatically light up.
Landing System Scales
![Landing System Scales](https://github.com/user-attachments/assets/58539df8-e232-4e9e-90ab-18ed862d5819)

Steps to reproduce
Setup an ILS approach anywhare you want and conduct approach.
leave LS P/B's off.
Check that amber LS is flashing when getting nearer to runway.
ARM LOC P/B - and check that LS deviation scales automatically appear, and LS P/B lights up on both EFIS.
Deselect LOC
Also turn off LS P/B's on both EFIS.
Check that amber LS is flashing when getting nearer to runway.
ARM APPR P/B - and check that LS deviation scales automatically appear, and LS P/B lights up on both EFIS.

2024-12-18 18:20 UTC, BravoMike99 commented
> Aircraft Version Stable
> 
> Build info "v0.12.0" Describe the bug When doing an ILS approach in the A380, and the LS P/B's on EFIS is not turned ON, the LS will constantly flash in amber which is correct, but doesn't automatically display the lateral and vertical deviation scales when LOC or APPR Mode is armed.
> 
> Expected behavior If LS P/B isn't selected when doing an ILS approach, it would automatically display the LOC and G/S deviation scales on both PFD's after arming the LOC P/B or APPR P/B, and the LS P/B's would automatically light up. Landing System Scales ![Landing System Scales](https://private-user-images.githubusercontent.com/186423382/397029244-58539df8-e232-4e9e-90ab-18ed862d5819.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NDYyMTYsIm5iZiI6MTczNDU0NTkxNiwicGF0aCI6Ii8xODY0MjMzODIvMzk3MDI5MjQ0LTU4NTM5ZGY4LWUyMzItNGU5ZS05MGFiLTE4ZWQ4NjJkNTgxOS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQxODE4MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTQwOWYxYTYxMGUxZDdjNjBmNTk1ZWMxNjI0M2Y5YmZkNTM5NzE5MDUzMzljZTIwNGNhNTA1M2M2NjQ3ZjVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rieRlt69SCnHs-pNESEejh4uUHPeltEHQIf7ImQmxR8)
> 
> Steps to reproduce Setup an ILS approach anywhare you want and conduct approach. leave LS P/B's off. Check that amber LS is flashing when getting nearer to runway. ARM LOC P/B - and check that LS deviation scales automatically appear, and LS P/B lights up on both EFIS. Deselect LOC Also turn off LS P/B's on both EFIS. Check that amber LS is flashing when getting nearer to runway. ARM APPR P/B - and check that LS deviation scales automatically appear, and LS P/B lights up on both EFIS.
> 
> For A320 it's different.

The original purpose of this PR is to just add the LS indicator on the PFD. The automatic LS selection is left for future work and should be addressed in a further PR.

2025-01-26 00:53 UTC, lukecologne requested changes

2025-01-26 00:53 UTC, lukecologne commented on fbw-a32nx/src/systems/instruments/src/PFD/LandingSystemIndicator.tsx
> +        fwcPhase !== 8 &&
Why are we checking for FWC flight phases here? I don't see why that is necessary

2025-01-26 00:53 UTC, lukecologne commented on fbw-a32nx/src/systems/instruments/src/PFD/LandingSystemIndicator.tsx
> +  private readonly landModeArmedOrActive = MappedSubject.create(
I think the condition should also include LOC modes (armed/capture/track) to account for the case when flying a LOC only approach

2025-01-26 00:53 UTC, lukecologne commented on fbw-a380x/src/systems/instruments/src/PFD/LandingSystemIndicator.tsx
> +      <text class="FontLargest Magenta MiddleAlign Blink9Seconds" ref={this.lsTitle} x="104" y="126">
Hm, not really related to this PR but I checked a ref and the ILS title did not flash when selecting LS (contrary to what the FCOM says). Not sure why, maybe it was because there was not an ILS approach explicitly selected (LS was activated, and then the ILS manually tuned via the MFD Navaids page)

2025-01-26 00:53 UTC, lukecologne commented on fbw-a380x/src/systems/instruments/src/PFD/LandingSystemIndicator.tsx
> +        fmgcPhase === FmgcFlightPhase.Approach &&
Same here as the A320 case

2025-01-26 00:53 UTC, lukecologne commented on fbw-a380x/src/systems/instruments/src/PFD/LandingSystemIndicator.tsx
> +class LsReminderIndicator extends DisplayComponent<{ bus: EventBus }> {
Interestingly the A380 FCOM does not mention the LS reminder. But I can't imagine it's not there tbh

2025-01-26 00:58 UTC, lukecologne commented on fbw-a32nx/src/systems/instruments/src/PFD/LandingSystemIndicator.tsx
> +        fwcPhase !== 8 &&
Disregard, sorry, just checked the ref again for the conditions

2025-01-26 13:15 UTC, BravoMike99 commented on fbw-a380x/src/systems/instruments/src/PFD/LandingSystemIndicator.tsx
> +      <text class="FontLargest Magenta MiddleAlign Blink9Seconds" ref={this.lsTitle} x="104" y="126">
I have now removed the blinking all together

2025-01-26 13:39 UTC, BravoMike99 commented on fbw-a380x/src/systems/instruments/src/PFD/LandingSystemIndicator.tsx
> +        fmgcPhase === FmgcFlightPhase.Approach &&
I have changed the A380 logic now to LOC or APPR active but kept the A320 the same, as the documents explicitly mention FCU APPR mode active and I don't have a better ref for the time being.

2025-01-26 13:40 UTC, BravoMike99 commented on fbw-a380x/src/systems/instruments/src/PFD/LandingSystemIndicator.tsx
> +class LsReminderIndicator extends DisplayComponent<{ bus: EventBus }> {
Its hidden 😛

2025-02-05 16:42 UTC, lukecologne approved these changes

2025-02-14 21:04 UTC, Jaronics commented
<!-- !! DO NOT REMOVE THIS LINE !! - QUALITY ASSURANCE REPORT -->
<!-- Refer to the https://docs.flybywiresim.com/dev-corner/qa-process/#reporting-on-tests for details about this template -->

<!-- Please use one or the other depending on your Discord Role -->
Quality Assurance Trainee Report

Discord Username  : Jaronics <!-- Use your username, not your display name! -->
Object of testing : #9668  <!-- PR Number -->
Aircraft          : A380X <!-- Choose only one -->
Tier of Testing   : 1
Date              : 14/02/2025 <!-- Date of test in DD/MM/YYYY format -->

Testing Process: 
1. Spawned on the runway. LS was displayed in amber when spawning and didn't go away when selecting the LS buttons to on. They layered over each other. (picture attached)
2. This issue could be fixed when turning on the APP button once in the air and letting the LS buttons turn on automatically.
2.1 Tried again, spawning at a gate. Issue still persists.
3. Armed APPROACH mode as normal and manually turned off the LS buttons. LS began to flash for 9sec.
4. Turned on the LS buttons manually. Amber LS disappeared correctly and was exchanged with the normal LS indications.
<!-- List the process - Required section --> 

Testing Results: 
Not Passed <!-- Required section --> 

Negatives:
Layering of the two indications on the ground needs to be looked into.
<!-- Ommit this section if none are found -->

Conclusions: 
PR performed as expected, except the issue when spawning in.
<!-- Ommit section if nothing to add -->

Media:
![Screenshot 2025-02-14 214330](https://github.com/user-attachments/assets/2b34b02d-8928-40e6-b6cc-0e0e5b4591e2)

<!-- Ommit this section if no media to add -->

2025-02-15 15:01 UTC, BravoMike99 commented
> Quality Assurance Trainee Report
> 
> Discord Username : Jaronics Object of testing : #9668 Aircraft : A380X Tier of Testing : 1 Date : 14/02/2025
> 
> Testing Process:
> 
> 1. Spawned on the runway. LS was displayed in amber when spawning and didn't go away when selecting the LS buttons to on. They layered over each other. (picture attached)
> 2. This issue could be fixed when turning on the APP button once in the air and letting the LS buttons turn on automatically.
>    2.1 Tried again, spawning at a gate. Issue still persists.
> 3. Armed APPROACH mode as normal and manually turned off the LS buttons. LS began to flash for 9sec.
> 4. Turned on the LS buttons manually. Amber LS disappeared correctly and was exchanged with the normal LS indications.
> 
> Testing Results: Not Passed
> 
> Negatives: Layering of the two indications on the ground needs to be looked into.
> 
> Conclusions: PR performed as expected, except the issue when spawning in.
> 
> Media: ![Screenshot 2025-02-14 214330](https://private-user-images.githubusercontent.com/144520077/413464115-2b34b02d-8928-40e6-b6cc-0e0e5b4591e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk2MzE5NTAsIm5iZiI6MTczOTYzMTY1MCwicGF0aCI6Ii8xNDQ1MjAwNzcvNDEzNDY0MTE1LTJiMzRiMDJkLTg5MjgtNDBlNi1iNmNjLTBlMGU1YjQ1OTFlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIxNVQxNTAwNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Y2Q1NTQ3MDliMDhjNzAwYTBkM2JjYjI0MTk1MGUyZTFkMTM3YTJiNWJlNWQ2NTQ2MDFmZTRkMTY1ODc0M2NhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ve7IQMa_ypyY0aSXvFse5gvPlhgesygTvRUfPjaElrM)

Thanks, I have added a fix which addresses the spawn in issue.

2025-02-26 17:55 UTC, Jaronics commented
<!-- !! DO NOT REMOVE THIS LINE !! - QUALITY ASSURANCE REPORT -->
<!-- Refer to the https://docs.flybywiresim.com/dev-corner/qa-process/#reporting-on-tests for details about this template -->

<!-- Please use one or the other depending on your Discord Role -->
Quality Assurance Trainee Report

Discord Username  : Jaronics <!-- Use your username, not your display name! -->
Object of testing : #9668  <!-- PR Number -->
Aircraft          : A380X <!-- Choose only one -->
Tier of Testing   : 1
Date              : 26/02/2025<!-- Date of test in DD/MM/YYYY format -->

Testing Process: 
1. Loaded the plane up at the gate and observed the layering issue. It has disappeared
2. Performed an ILS approach without the LS displayed. LS Flashed 9 times in amber.
3. Tried the same with LOC only mode 
<!-- List the process - Required section --> 

Testing Results: 
Passed <!-- Required section --> 

Negatives:       
None
<!-- Ommit this section if none are found -->

Conclusions: 
<!-- Ommit section if nothing to add -->

Media:
<!-- Ommit this section if no media to add -->

2025-02-26 18:01 UTC, merged